In [24]:
from scipy.stats import zscore
import pandas as pd

df = pd.read_csv('amazon.csv')
df = df.dropna()
print(df.head())

   product_id                                       product_name  \
0  B07JW9H4J1  Wayona Nylon Braided USB to Lightning Fast Cha...
1  B098NS6PVG  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
2  B096MSW6CT  Sounce Fast Phone Charging Cable & Data Sync U...
3  B08HDJ86NZ  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...
4  B08CF3B7N1  Portronics Konnect L 1.2M Fast Charging 3A 8 P...

                                            category discounted_price  \
0  Computers&Accessories|Accessories&Peripherals|...             ₹399
1  Computers&Accessories|Accessories&Peripherals|...             ₹199
2  Computers&Accessories|Accessories&Peripherals|...             ₹199
3  Computers&Accessories|Accessories&Peripherals|...             ₹329
4  Computers&Accessories|Accessories&Peripherals|...             ₹154

  actual_price discount_percentage rating rating_count  \
0       ₹1,099                 64%    4.2       24,269
1         ₹349                 43%    4.0       43,994
2       ₹1,899                 90%    3.9        7,928
3         ₹699                 53%    4.2       94,363
4         ₹399                 61%    4.2       16,905

                                       about_product  \
0  High Compatibility : Compatible With iPhone 12...
1  Compatible with all Type C enabled devices, be...
2  【 Fast Charger& Data Sync】-With built-in safet...
3  The boAt Deuce USB 300 2 in 1 cable is compati...
4  [CHARGE & SYNC FUNCTION]- This cable comes wit...

                                             user_id  \
0  AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...
1  AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...
2  AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...
3  AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...
4  AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...

                                           user_name  \
0  Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...
1  ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...
2  Kunal,Himanshu,viswanath,sai niharka,saqib mal...
3  Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...
4  rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...

                                           review_id  \
0  R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...
1  RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...
2  R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...
3  R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...
4  R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...

                                        review_title  \
0  Satisfied,Charging is really fast,Value for mo...
1  A Good Braided Cable for Your Type C Device,Go...
2  Good speed for earlier versions,Good Product,W...
3  Good product,Good one,Nice,Really nice product...
4  As good as original,Decent,Good one for second...

                                      review_content  \
0  Looks durable Charging is fine tooNo complains...
1  I ordered this cable to connect my phone to An...
2  Not quite durable and sturdy,https://m.media-a...
3  Good product,long wire,Charges good,Nice,I bou...
4  Bought this instead of original apple, does th...

                                            img_link  \
0  https://m.media-amazon.com/images/W/WEBP_40237...
1  https://m.media-amazon.com/images/W/WEBP_40237...
2  https://m.media-amazon.com/images/W/WEBP_40237...
3  https://m.media-amazon.com/images/I/41V5FtEWPk...
4  https://m.media-amazon.com/images/W/WEBP_40237...

                                        product_link
0  https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1  https://www.amazon.in/Ambrane-Unbreakable-Char...
2  https://www.amazon.in/Sounce-iPhone-Charging-C...
3  https://www.amazon.in/Deuce-300-Resistant-Tang...
4  https://www.amazon.in/Portronics-Konnect-POR-1...

In [26]:
#Information generale sur le dataset

df_shape = df.shape
print("Nombre de lignes du dataset:", df_shape[0])
print("Nombre de colonnes:", df_shape[1])

df.dtypes

Nombre de lignes du dataset: 1463
Nombre de colonnes: 16

product_id             object
product_name           object
category               object
discounted_price       object
actual_price           object
discount_percentage    object
rating                 object
rating_count           object
about_product          object
user_id                object
user_name              object
review_id              object
review_title           object
review_content         object
img_link               object
product_link           object
dtype: object

In [27]:
#Changement de type dans les colonnes numeriques

df["discounted_price"] = (df["discounted_price"].str.replace("₹", "", regex=False).str.replace("," , "", regex=False).astype(float))

df["actual_price"] = (
    df["actual_price"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)

In [28]:
#Discount

df["discount_percentage"] = (
    df["discount_percentage"].str.replace("%", "", regex=False).astype(float)
)

In [29]:
#Ratings
df["rating"] = pd.to_numeric(df["rating"], errors="coerce")

df["rating_count"] = (
    df["rating_count"]
    .str.replace(",", "", regex=False)
    .astype(int)
)

In [30]:
print(df[["actual_price","discounted_price","discount_percentage", "rating", "rating_count"]].head())

   actual_price  discounted_price  discount_percentage  rating  rating_count
0        1099.0             399.0                 64.0     4.2         24269
1         349.0             199.0                 43.0     4.0         43994
2        1899.0             199.0                 90.0     3.9          7928
3         699.0             329.0                 53.0     4.2         94363
4         399.0             154.0                 61.0     4.2         16905

In [31]:
#Verification des doublons 

print("Lignes repetees",df.duplicated().sum())
print("Reviews repetees", df['review_id'].duplicated().sum())
print("Produits repetees",df['product_id'].duplicated().sum())

Lignes repetees 0
Reviews repetees 271
Produits repetees 114

In [32]:
df[df['review_id'].duplicated(keep=False)].head(20)

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.00,1099.0,64.0,4.2,24269,High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.00,349.0,43.0,4.0,43994,"Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.00,1899.0,90.0,3.9,7928,【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.00,699.0,53.0,4.2,94363,The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.00,399.0,61.0,4.2,16905,[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...
5,B08Y1TFSP6,pTron Solero TB301 3A Type-C Data and Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,149.00,1000.0,85.0,3.9,24871,Fast Charging & Data Sync: Solero TB301 Type-C...,"AEQ2YMXSZWEOHK2EHTNLOS56YTZQ,AGRVINWECNY7323CW...","Jayesh,Rajesh k.,Soopy,amazon customer,Aman,Sh...","R7S8ANNSDPR40,R3CLZFLHVJU26P,RFF7U7MPQFUGR,R1M...","It's pretty good,Average quality,very good and...","It's a good product.,Like,Very good item stron...",https://m.media-amazon.com/images/I/31wOPjcSxl...,https://www.amazon.in/Solero-TB301-Charging-48...
6,B08WRWPM22,"boAt Micro USB 55 Tangle-free, Sturdy Micro US...",Computers&Accessories|Accessories&Peripherals|...,176.63,499.0,65.0,4.1,15188,It Ensures High Speed Transmission And Chargin...,"AG7C6DAADCTRQJG2BRS3RIKDT52Q,AFU7BOMPVJ7Q3TTA4...","Vivek kumar,Amazon Customer,SARTHAK,Chiranjeev...","R8E73K2KWJRDS,RSD0JTIIWQQL8,R64CRSTE9SLW1,R2FR...","Long durable.,good,Does not charge Lenovo m8 t...",Build quality is good and it is comes with 2 y...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/boAt-Micro-USB-Tangle-Fr...
7,B08DDRGWTJ,MI Usb Type-C Cable Smartphone (Black),Computers&Accessories|Accessories&Peripherals|...,229.00,299.0,23.0,4.3,30411,1m long Type-C USB Cable|Sturdy and Durable. W...,"AHW6E5LQ2BDYOIVLAJGDH45J5V5Q,AF74RSGCHPZITVFSZ...","Pavan A H,Jayesh bagad,Shridhar,rajendran,karu...","R2X090D1YHACKR,R32ZCIH9AFNJ60,R3N57EVVG0EHAF,R...","Worth for money - suitable for Android auto,Go...",Worth for money - suitable for Android auto......,https://m.media-amazon.com/images/I/31XO-wfGGG...,https://www.amazon.in/MI-MTCY001IN-USB-Type-C-...
8,B008IFXQFU,"TP-Link USB WiFi Adapter for PC(TL-WN725N), N1...",Computers&Accessories|NetworkingDevices|Networ...,499.00,999.0,50.0,4.2,179691,USB WiFi Adapter —— Speedy wireless transmissi...,"AGV3IEFANZCKECFGUM42MRH5FNOA,AEBO7NWCNXKT4AESA...","Azhar JuMan,Anirudh Sood,Hari Krishnan PS,Akas...","R1LW6NWSVTVZ2H,R3VR5WFKUS15C5,R2F6GC79OYWUKQ,R...",Works on linux for me. Get the model with ante...,I use this to connect an old PC to internet. I...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/TP-Link-TL-WN725N-150Mbp...
9,B082LZGK39,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.00,299.0,33.0,4.0,43994,Universal Compatibility – It is compatible wit...,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
10,B08CF3D7QR,Portronics Konnect L POR-1081 Fast Charging 3A...,Computers&Accessories|Accessories&Peripherals|...,154.00,339.0,55.0,4.3,13391,[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AGYLPKPZHVYKKZHOTHCTYVEDAJ4A,AGTTU64JMX722LYCN...","Tanya,Anu,Akshay,Vishal Sagara Shetty,Swatilek...","R11MQS7WD9C3I0,R2AKH69XQY8BY4,R8GBOLYUN5UP6,R1...",Good for fast charge but not for data transfer...,The cable is efficient in fast charging but in...,https://m.media-amazon.com/images/I/31dJ+lXJq3...,https://www.amazon.in/Portronics-POR-1081-Char...
11,B0789LZTCJ,boAt Rugged v3 Extra Tough Unbreakable Braided...,Computers&Accessories|Accessories&Peripherals|...,299.00,799.0,63.0,4.2,94363,The boAt rugged cable features our special tou...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41SDfuK7L2...,https://www.amazon.in/Rugged-Extra-Tough-Unbre...
12,B07KSMBL2H,AmazonBasics Flexible Premium HDMI Cable (Blac...,"Electronics|HomeTheater,TV&Video|Accessories|C...",219.00,700.0,69.0,4.4,426973,"Flexible, lightweight HDMI cable for connectin...","AEYJ5I6JZZPOJB6MGWRQOHRQLPSQ,AFY5TVFOMVHGBPBTI...","Rishav Gossain,Shashank Mallamraju,Purnendu,gu...","R1FKOKZ3HHKJBZ,R2WNMZI1EXTA0H,RCA1M3W4RIXUR,R3...","It's quite good and value for money,Works well...",I am using it for 14 days now. The experience ...,https://m.media-amazon.com/images/I/41nPYaWA+M...,https://www.amazon.in/AmazonBasics-Flexible-HD...
13,B085DTN6R2,Portronics Konnect CL 20W POR-1067 Type-C to 8...,Computers&Accessories|Accessories&Peripherals|...,350.00,899.0,61.0,4.2,2262,[20W PD FAST CHARGING]-It’s supports 20W PD qu...,"AGUAYQHARAKR2VZTRP276KAGETKQ,AFKTST2773VUOKUHE...","Priya,Mansi,Plaban,Vivek,Taufique Ahmed,Pravee...","R1QETDIPRCX4S0,RARQYQ8POOFA9,R952F931MCOR5,R3L...","Works,Nice Product,Fast Charging as original,G...",Definitely isn’t as good as the original cord ...,https://m.media-amazon.com/images/I/31J6qGhAL9...,https://www.amazon.in/Portronics-Konnect-Deliv...
14,B09KLVMZ3B,Portronics Konnect L 1.2M POR-1401 Fast Chargi...,Computers&Accessories|Accessories&Peripherals|...,159.00,399.0,60.0,4.1,4768,[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AF2XXVO7JUBUVAOBTJ3MNH4DGUFQ,AH6VDJLLPBXKCWXML...","Deepaak Singh,siva k.,MUNDATH BALGOPAL,BOOPATH...","R20XIOU25HEX80,R2X55FA2EEUEYM,R393Z224NBTDLN,R...","Great but,Worked well for 6 six months that’s ...",Loosing charging cable of apple is costly affa...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...
15,B083342NKJ,MI Braided USB Type-C Cable for Charging Adapt...,Computers&Accessories|Accessories&Peripherals|...,349.00,399.0,13.0,4.4,18757,1M Long Cable. Usb 2.0 (Type A)|Toughened Join...,"AGSGSRTEZBQY64WO2HKQTV7TWFSA,AEYD5HVYAJ23CR6PT...","Birendra ku Dash,Aditya Gupta,Abdulla A N,Deep...","R2JPQNKCOE10UK,RQI80JG2WZXNF,R2LYZ4CUWPMUJN,R1...","Good product,using this product 8months It is ...","I like it 👍👍,Best charging power . I used this...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Mi-Braided-USB-Type-C-Ca...
16,B0B6F7LX4C,MI 80 cm (32 inches) 5A Series HD Ready Smart ...,"Electronics|HomeTheater,TV&Video|Televisions|S...",13999.00,24999.0,44.0,4.2,32840,"Note : The brands, Mi and Xiaomi, are part of ...","AHEVOQADJSSRX7DS325HSFLMP7VQ,AG7XYZRCSKX6G2OLO...","Manoj maddheshiya,Manoj Kumar Sahoo,Saumil s.,...","R13UTIA6KOF6QV,R2UGDZSGFF01K7,RHHIZ45VYU5X6,R1...",It is the best tv if you are getting it in 10-...,Pros- xiomi 5a is best in budget-Nice picture ...,https://m.media-amazon.com/images/I/51fmHk3km+...,https://www.amazon.in/MI-inches-Ready-Android-...
17,B082LSVT4B,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,249.00,399.0,38.0,4.0,43994,"Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/I/41d84o5-M-...,https://www.amazon.in/Ambrane-Unbreakable-Char...
19,B08DPLCM6T,LG 80 cm (32 inches) HD Ready Smart LED TV 32L...,"Electronics|HomeTheater,TV&Video|Televisions|S...",13490.00,21990.0,39.0,4.3,11976,Resolution: HD Ready (1366x768) | Refresh Rate...,"AHBNKB74LGTYUOKPAJBSKNFV45CA,AFIECTV45ADX5YPTE...","NIRMAL.N,Manoj kumar,SOMNATH DAS,Harsha,Pradhu...","R2PNR69G0BQG2F,R31A0WWDEYMKEW,R2C4XEWFLVU7JV,R...","Sound quality,Very nice,Value for money,Good,G...","LG was always Good , correct delivery, good se...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/LG-inches-Ready-Smart-32...
20,B09C6HXFC1,Duracell USB Lightning Apple Certified (Mfi) B...,Computers&Accessories|Accessories&Peripherals|...,970.00,1799.0,46.0,4.5,815,Supports Ios Devices With Max Output Up To 2.4...,"AFNYIBWKJLJQKY4BGK77ZOTVMORA,AFCTNNMP2LZLY5466...","Prasannavijayaraghavan G.,Preet Sikka,Theeban ...","R12D1BZF9MU8TN,R32MNCWO5LGFCG,RZU3UK8OZKD6X,R3...","Good cable for car,Good substitute for orginal...",I trust this product! Works well with car play...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/DURACELL-Lightning-Certi...

In [33]:
#Enlever les doublons
df = df.drop_duplicates(subset='review_id')

In [34]:
print(df.duplicated().sum())
print(df['review_id'].duplicated().sum())

0
0

In [35]:
#Verification des valeurs anormales
df['z_price'] = zscore(df['actual_price'])

outliers = df[abs(df['z_price']) > 3]
print(outliers[['actual_price', 'product_name']])

#On regarde que il y a des valeurs avec des prix hautes, ceci provoque un z_score> 3, mais sur les categories comme TV, etc... Alors les valeurs sont legitimes et on as pas besoin de les supprimer

      actual_price                                       product_name
38         45999.0  OnePlus 126 cm (50 inches) Y Series 4K Ultra H...
41         34999.0  Mi 108 cm (43 inches) Full HD Android LED TV 4...
61         47900.0  Samsung 108 cm (43 inches) Crystal 4K Neo Seri...
94         40990.0  TCL 100 cm (40 inches) Full HD Certified Andro...
108        65000.0  VU 139 cm (55 inches) The GloLED Series 4K Sma...
123        44990.0  Hisense 108 cm (43 inches) 4K Ultra HD Smart C...
135        49990.0  LG 108 cm (43 inches) 4K Ultra HD Smart LED TV...
150        65000.0  VU 138 cm (55 inches) Premium Series 4K Ultra ...
216        59999.0  OnePlus 138.7 cm (55 inches) U Series 4K LED S...
231        49999.0  MI 108 cm (43 inches) 5X Series 4K Ultra HD LE...
232        56790.0  Sansui 140cm (55 inches) 4K Ultra HD Certified...
249       139900.0  Sony Bravia 164 cm (65 inches) 4K Ultra HD Sma...
280        34990.0  Toshiba 108 cm (43 inches) V Series Full HD Sm...
286        35000.0  VU 108 cm (43 inches) Premium Series Full HD S...
292        54990.0  Hisense 126 cm (50 inches) Bezelless Series 4K...
295        50999.0  Kodak 139 cm (55 inches) 4K Ultra HD Smart LED...
306        42999.0  Kodak 126 cm (50 inches) Bezel-Less Design Ser...
323        51990.0  TCL 108 cm (43 inches) 4K Ultra HD Certified A...
326        50000.0  AmazonBasics 108 cm (43 inches) 4K Ultra HD Sm...
332        69999.0  MI 138.8 cm (55 inches) 5X Series 4K Ultra HD ...
394        34999.0  iQOO Neo 6 5G (Dark Nova, 8GB RAM, 128GB Stora...
410        38999.0  OnePlus 10R 5G (Forest Green, 8GB RAM, 128GB S...
533        49999.0  OnePlus 10T 5G (Moonstone Black, 8GB RAM, 128G...
544        39990.0  iQOO 9 SE 5G (Sunset Sierra, 8GB RAM, 128GB St...
568        74999.0  Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...
976        37999.0  Xiaomi Pad 5| Qualcomm Snapdragon 860| 120Hz R...
1014       59890.0  Lenovo IdeaPad 3 11th Gen Intel Core i3 15.6" ...
1182       59900.0  Coway Professional Air Purifier for Home, Long...
1306       59900.0  ECOVACS DEEBOT N8 2-in-1 Robotic Vacuum Cleane...
1354       75990.0  LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...

In [36]:
#Conversion des prix en euros

INR_TO_EUR = 0.011

df['actual_price_eu'] = df['actual_price'] * INR_TO_EUR
df['discounted_price_eu'] = df['discounted_price'] * INR_TO_EUR

df[['actual_price_eu', 'discounted_price_eu']].head()

   actual_price_eu  discounted_price_eu
0           12.089                4.389
1            3.839                2.189
2           20.889                2.189
3            7.689                3.619
4            4.389                1.694